---
- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true
  notify:
    - "Install pip requests"

- name: Disable systemd-resolved.service
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: false

- name: Create parent directory of volume
  ansible.builtin.file:
    path: /root/pi-hole
    state: directory
    mode: 640
  notify:
    - "Create /etc/pihole volume"
    - "Create /etc/dnsmasq.d volume"

- name: Create latest Pi-hole container
  community.docker.docker_container:
    name: pi-hole
    image: pihole/pihole:latest
    restart: true
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    env:
      TZ: "Asia/Tokyo"
      WEBPASSWORD: "{{ WEBPASSWORD }}"
      FTLCONF_LOCAL_IPV4: "{{ FTLCONF_LOCAL_IPV4 }}"
      PIHOLE_DNS: "{{ PIHOLE_DNS }}"
    volumes:
      - /root/pi-hole/etc-pihole:/etc/pihole
      - /root/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d

- name: Create Watchtower container
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower:latest
    restart: true
    env:
      TZ: "Asia/Tokyo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
