---
- name: Create parent directory of volume
  ansible.builtin.file:
    path: /root/pi-hole
    state: directory

- name: Create /etc/pihole volume
  ansible.builtin.file:
    path: /root/pi-hole/etc-pihole
    state: directory

- name: Create /etc/dnsmasq.d volume
  ansible.builtin.file:
    path: /root/pi-hole/etc-dnsmasq.d
    state: directory

- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- name: Install pip requests
  ansible.builtin.pip:
    name: requests
    state: latest

- name: Remove Pi-hole container
  community.docker.docker_container:
    name: pi-hole
    state: absent

- name: Remove Pi-hole image
  community.docker.docker_image:
    name: pihole/pihole:latest
    state: absent

- name: Disable systemd-resolved.service
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: false

- name: Create latest Pi-hole container
  community.docker.docker_container:
    name: pi-hole
    image: pihole/pihole
    restart: true
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    env:
      TZ: "Asia/Tokyo"
      WEBPASSWORD: "{{ WEBPASSWORD }}"
      FTLCONF_LOCAL_IPV4: "{{ FTLCONF_LOCAL_IPV4 }}"
      PIHOLE_DNS: "{{ PIHOLE_DNS }}"
    volumes:
      - /root/pi-hole/etc-pihole:/etc/pihole
      - /root/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d
